### ISSUE TITLE
Develop a tool to copy the blob data of Azure storage in an ASP.NET Website.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/CloudOS#1]
# Requirement
I'm currently planning about VHD template deployment internal services using Microsoft Azure.
I want to develop a tool to copy the blob data of Azure storage in an ASP.NET Website.

I've uploaded the specification to the following URL.
https://github.com/OpenTouryoProject/CloudOS/blob/develop/documents/AzureStorageBlobDataCopyWebsite/Specification_EN.xlsx

**Comment by daisukenishino** [comment]
# About Azure Blob Storage
## Subdirectories
- Using Subdirectories in Windows Azure Blob Storage  
http://stackoverflow.com/questions/14328493/using-subdirectories-in-windows-azure-blob-storage  
It is possible to use subdirectories in Azure Blob Storage.  
But I do not want to use the Subdirectories this time.

## SDK or PowerShell
- Copy Blobs With StartCopyFromBlob and Track its Progression Using CopyState  
https://alexandrebrisebois.wordpress.com/2013/06/25/copy-blobs-with-startcopyfromblob-and-track-its-progression-using-copystate/
Please check the above sample code.  
There is a possibility that can be developed in the Azure SDK.  
Therefore, there is a possibility that does not use PowerShell.

## Storage account
- Region of the copy source and copy destination.
  - Should be selected one region at copy source.
  - Region of copy (upload) destination can be selected as multiple regions.  
If you have selected more than one, it will be copied (uploaded) to Azure storage of multiple regions.
- Azure storage that will be stored the document.  
Azure storage account for storing the document is only one account(one region).  
Therefore, this storage account's account name and storage key and container name is defined in app.config (URL of AzureStorage BLOB files is consisted account name and container name).
- Four of azure storage account is defined in app.config.
  - One of account is used to save the document to a specific Azure storage.
  - The rest of the account will be used to store the VHD file to Azure storage of each region.
- In the case of middle test phase.  
You should create a storage account corresponding each region. In this time, not required to divide the region. Because, these storage account can be assumed that related to each region.

**Comment by daisukenishino** [comment]
Maybe OK.
There is a need that operate accordance with our requirements.
After that, the code at github comment must be enclosed in "```C#" and "```".

**Comment by kishoreandukuri** [comment]
sure Nishino-san

**Comment by daisukenishino** [comment]
# Folder structure
I think this is problem that there is DLL project under the WebSite.
However, files on the WebSite can not be changed to Embedded Resource.
Therefore, I want to change in the such following folder structure.

- Programs
   - AzureStorageBlobDataCopyTool
      - Website
         - Alias on IIS is AzureStorageBlobDataCopyWebsite.
         - Including the only project of one of ASP.NET WebSite
      - AsyncProcess ( this project's output is dll )
         - Class Library Project that is hosted in AsyncProcessingService.
         - Do not add the DLL to the repository.
         - DLL is deployed to AsyncProcessingService's "current directory" after the build.
      - Sql ( this project's output is dll )
         - Class Library Project that contains the SQL used from WebSite.
         - It is project-referenced from Website.
         - Do not add the DLL to the repository.
         - DLL is deployed to WebSite's bin folder after the build.

## Supplement of above
- DLL of AsyncProcess is used from AsyncProcessService.
- However, AsyncProcessService do not refer to the DLL of AsyncProcess.
- This is because, AsyncProcessService calls the DLL of B/D layer of AsyncProcess by late bound using the communication control function.
- DLL of AsyncProcess of B/D layer, corresponding to the user program on the specifications of AsyncProcessService.
- This DLL is located in the "current directory" of AsyncProcessService after the build by build bat.

## Q&A
>(1) We will create AsyncProcess new class library in AzureStorageBlobDataCopyTool.

OK.

>(2) We will  include LayerB and LayerD from user program(AsyncSvc_Sample) into AsyncProcess class library.

"AsyncSvc_Sample" is also "user program".

- But, the "user program" of here is written in specification of "AsyncProcessService".  
https://github.com/OpenTouryoProject/OpenTouryoDocuments/tree/develop/documents/1_User_Guide/en/AsyncProcessingService
- "user program" is B/D layer to perform the asynchronous processing  
(Is drawn in the form of gears in specification.).

You should add a above "user program" project to "/programs/AzureStorageBlobDataCopyTool/AsyncProcess" folder.

And, B/D layer for registering asynchronous tasks are also "user program".

But, B/D layer for registering asynchronous tasks are located in the following.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/AsyncProcessingService
Because, this components will be used from the "user programs" like "AsyncSvc_Sample" for registering asynchronous tasks.

>(3) After build it, we will add this reference into AsyncProcessingService current directory like  bin debug AsyncProcess.dll )

You don't need to add "references" to project,
because to call in latebound by "communication control function".

>(4) Then we will refer from AsyncProcessingService bin debug folder to AzureCopytoolwebsite.

After you build the AsyncProcessingServic,
In the build batch, build the AsyncProcess project,
and copy the AsyncProcess.dll to "AsyncProcessingService/bin/debug/" folder.

**Comment by daisukenishino** [comment]
# Changes about SQL project.
## About SQL file
### SQL file location
root/files/resource/Sql/sqlserver/AsyncProcessingService/

### How to add SQL file
Add as "linked file".

- Adding or linking existing files to a project in Visual Studio .NET  
http://support.microsoft.com/en-us/kb/306234

## How to load the SQL
SQL.dll that is output from the SQL project is not the entry assembly.
Therefore, you can load the SQL using the [LoadAsString](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/IO/EmbeddedResourceLoader.cs#L197) method,
And to set the SQL using the [SetSqlByCommand](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Dao/BaseDao.cs#L134) method.

**Comment by SandeepNayak077** [comment]
HODC will do research on the EmbeddedResourceLoader.LoadAsString method and the Dao.SetSqlByCommand method

After that, HODC will implement the same in the AsyncProcessingService project

Please confirm

**Comment by daisukenishino** [comment]
Roger that

**Comment by daisukenishino** [comment]
# Changes about SQL project.
## Abolish the SQL project.
- Copy tool own SQL files should be placed in the [/AzureStorageBlobDataCopyTool/Sql/](https://github.com/OpenTouryoProject/CloudOS/tree/develop/programs/AzureStorageBlobDataCopyTool/Sql/) folder.
- And, is moved to [/root/files/resource/Sql/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/resource/Sql/) folder at runtime.
- And, be loaded using the [Dao.SetSqlByFile](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Dao/BaseDao.cs#L117) method from [location pointed to SqlTextFilePath parameter](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/resource/Sql/).

## Instead, using Business project.
Asynchronous processing service own SQL files will be embedded into [Business project](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business.csproj) as a [linked file](http://support.microsoft.com/en-us/kb/306234). Please refer to [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/58#issuecomment-91582524) for details.

**Comment by SandeepNayak077** [comment]
HISOL > Copy tool own SQL files should be placed in the /AzureStorageBlobDataCopyTool/Sql/ folder
HODC Understanding:
Since, there are two types of files in Embedded Resource project (Sql.dll)
        - sql (inludes SQL query files related to CopyTool website)
        - xml (inluded MSGDefinition.xml file)

HODC will move only the 'sql' folder in the Embedded Resource project (Sql.dll) from the CopyTool website to the following location and we will keep the 'xml' folder.
Location: /AzureStorageBlobDataCopyTool/Sql/

HISOL > And, is moved to /root/files/resource/Sql/ folder at runtime.
HODC Question:
Does HODC need to implement the code (In the 'Aplication_Start()' event) to copy SQL files from '/AzureStorageBlobDataCopyTool/Sql/' location to '/root/files/resource/Sql/' location?
or
Does the SQL files will be copied manually?

Please confirm

**Comment by SandeepNayak077** [comment]
'Good-To-Have'
Since the serialized data is not used by 'AsyncProcessingService' project 
HODC thinks that the implementation of 'Serialize' and 'Deseriaze' can be done in 'AsyncProcess.dll' of the CopyTool project.

HODC suggestion:
- Serialize data to base64 string in the code behind of user screen.
- Get serialized data and is passed to the UserProgram ('AsyncProcess.dll' of CopyTool project) using 'AsyncProcessingServiceParameterValue' class 
- Deserialize data in the 'AsyncProcess.dll' of CopyTool project

**Comment by daisukenishino** [comment]
# CR ()
##
When it is "status=End" or "status=Abort", then disable 'Abort' button.

## Check for input length.
I want to implement that check for input length.

## Internationalization
### How to Implement
It implements in the [same way as tools]().

### 
The results of the discussion, it was decided to implement in of Global.asax.
The setting of this place is to work after the setting of uiCulture of globalization section of web.config.

Some of the browser to send jp instead ja-jp as Accept-Language attribute.
Currently, it is preparing a resource file of ja-jp is not a resource file of jp.
Originally, it was to prepare a resource file from the culture closer to the root in order.
Therefore, if it is detected jp to Accept-Language attribute, set the ja-jp to Thread.CurrentThread.CurrentUICulture.

##

**Comment by SandeepNayak077** [comment]
Dear Nishino-san

Please correct the above comment with "ja" instead of "jp"
Because browser's Accept-Language attribute includes either "ja" or "ja-JP"

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

1) />>Copied storagekey is taken from each time Web.config.
HODC is taking Copied storagekey is taken from each time app.config.
Shall we take from web.config instead of app.config?

2) />>Copied storagekey not registered in the DB at AdminScreen_ProvidedVHDList.aspx.
Shall we register StorageAccount name also along with storagekey?

Please let us know.

**Comment by daisukenishino** [comment]
(1) web.config ---> app.config
(2) Delete the storagekey field from the vhdregion table.

**Comment by SandeepNayak077** [comment]
Thank you for your valuable comments Nishino-san

**Comment by daisukenishino** [comment]
# Bug report

## Registered VHD to the copy web site becomes Length 0.
Steps to Reproduce
- Open AdminScreen_ProvidedVHDList.aspx.
- At first, select two regions, and select one vhd, and pressing the Add Record button.
- After selecting the record registered in the above, and presses the button Add VHD.
- Then add another vhd by Browse button, pressing the Update Record button.
- Then, length (size) of vhd that you added in the first step will be set to 0.

## After the Session TimeOut also, can be operated.
We think that it should be added the process of discarding the authentication ticket of ASP.NET Forms authentication at the error screen.

## Service stop processing of AsyncProcessingService will not complete.
I do not know why not complete in the code of the current OnStop events.
Please debugging the processing of OnStop event.

**Comment by daisukenishino** [comment]
We have updated the [specifications](
https://github.com/OpenTouryoProject/CloudOS/blob/develop/documents/AzureStorageBlobDataCopyWebsite/Specification_EN.xlsx). Please check.

**Comment by daisukenishino** [comment]
We have updated the [specifications](
https://github.com/OpenTouryoProject/CloudOS/blob/develop/documents/AzureStorageBlobDataCopyWebsite/Specification_EN.xlsx). Please check the writing in red.

**Comment by daisukenishino** [comment]
# Specification of the event  at the "Admin screen - Provide VHD List".
following is written about specification of "Add Record" and "Update Record" and "Delete Record" event.

```C#
if ( "Add Record" is pressed ) {
    
    if ( "Document name" has been input )
    {
        Register the URL of the document file to DB.
        
        // Write the document file to the Blob.
        if ( "Upload document" has been input )
        {
            Write the document file to the Blob.
        }
        else
        {
            // Do nothing.
        }
    }
    else // "Document name" has not been input.
    {
        // Blob is not operated.
    }
}
if ( "Update Record" is pressed ) {
    
    if ( "Document name" has been input )
    {
        Update the URL of the document file to DB.
        
        // Write the document file to the Blob.
        if ( "Upload document" has been input )
        {
            Write the document file to the Blob.
        }
        else
        {
            // Do nothing.
        }
            
        if ( Different from the previous "Document name" )
        {   
            // Choose to delete previous "Document name" file at the BLOB.
            if ( Not using the previous "Document name" file in other VHD Name. )
            {
                Delete previous "Document name" file at the BLOB.
            }
            else
            {
                // Do nothing.
                // Not delete previous "Document name" file at the BLOB.
                // This is because using the previous "Document name" file.
            }
        }
        else 
        {
            // Do nothing ( Not update ).
            // - This is new registration,
            // - or, the same as the previous "Document name".
        }
    }
    else // "Document name" has not been input.
    {
        Delete the URL of the document to DB.
        
        // Blob is not operated.
        
        // Choose to delete previous "Document name" file at the BLOB.
        if ( Not using the previous "Document name" file in other VHD Name. )
        {
            Delete previous "Document name" file at the BLOB.
        }
        else
        {
            // Do nothing.
            // Not delete previous "Document name" file at the BLOB.
            // This is because using the previous "Document name" file.
        }
    }
}
else if ( "Delete Record" is pressed ) {
    
    // Choose to delete previous "Document name" file at the BLOB.
    if ( Not using the previous "Document name" file in other VHD Name. )
    {
        Delete previous "Document name" file at the BLOB.
    }
    else
    {
        // Do nothing.
        // Not delete previous "Document name" file at the BLOB.
        // This is because using the previous "Document name" file.
    }
}
```

**Comment by SandeepNayak077** [comment]
\> Register the URL of the document file to DB.
\> Update the URL of the document file to DB.

If the "Upload document" has not been input, then incorrect data is Registered/Updated in the DB

\<Our Suggestion>
If the "Document name" has been input, but If the "Upload document" has not been input
Then display error message "Please select a file to upload"

Please confirm

**Comment by daisukenishino** [comment]
>\<Our Suggestion>
>If the "Document name" has been input, but If the "Upload document" has not been input
>Then display error message "Please select a file to upload"

Thank you proposed.
But, there is no problem in this specification.

Because, There is possibility
 that only want to edit the records without document file upload.

**Comment by SandeepNayak077** [comment]
\> Thank you proposed.
\> But, there is no problem in this specification.

Thank you for the replay

\<Our understanding>
Display error message is not needed

Please confirm
